### ISSUE TITLE
how to resolve this error

### ISSUE THREAD

**Issue by hblink** [MervinPraison/PraisonAI#152]
i followed the instruction, but get this error when trying praisonai coe
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/papa/praisonai/myvenv/lib/python3.11/site-packages/praisonai/__init__.py", line 5, in <module>
    from .cli import PraisonAI
  File "/home/papa/praisonai/myvenv/lib/python3.11/site-packages/praisonai/cli.py", line 23, in <module>
    from chainlit.cli import chainlit_run
  File "/home/papa/praisonai/myvenv/lib/python3.11/site-packages/chainlit/__init__.py", line 26, in <module>
    from chainlit.action import Action
  File "/home/papa/praisonai/myvenv/lib/python3.11/site-packages/chainlit/action.py", line 5, in <module>
    from chainlit.telemetry import trace_event
  File "/home/papa/praisonai/myvenv/lib/python3.11/site-packages/chainlit/telemetry.py", line 12, in <module>
    from chainlit.config import config
  File "/home/papa/praisonai/myvenv/lib/python3.11/site-packages/chainlit/config.py", line 36, in <module>
    FILES_DIRECTORY.mkdir(exist_ok=True)
  File "/usr/lib/python3.11/pathlib.py", line 1117, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/papa/.praison/.files'

**Comment by Rom-1T** [comment]
I had the same problem, just create both of those folder in your /home/papa. This might be caused you have installed it for an user who does not have access to root rights.

**Comment by MervinPraison** [comment]
@hblink Alternatively `export CHAINLIT_APP_ROOT=your/desired/path `

@Rom-1T Thanks for your contribution.
