### ISSUE TITLE
CHAINLIT_JWT_SECRET Key not found

### ISSUE THREAD

**Issue by scalenow** [MervinPraison/PraisonAI#195]
Getting the error  ValueError: You must provide a JWT secret in the environment to use authentication.

chainlit create-secret has been number of times and JWT secret key has been exported .

Please help

export
CHAINLIT_JWT_SECRET='hxd6ON7UBIBoV2jE^~^>~1sn02Otu-jcS:hlZn-H0y.U0q@^8%RIf%:Atbk,wmm0'
COLORFGBG='15;0'
COLORTERM=truecolor
COMMAND_MODE=unix2003
CONDA_DEFAULT_ENV=praison
CONDA_EXE=/Users/abhichaturvedi/miniconda3/bin/conda
CONDA_PREFIX=/Users/abhichaturvedi/miniconda3/envs/praison
CONDA_PREFIX_1=/Users/abhichaturvedi/miniconda3
CONDA_PROMPT_MODIFIER='(praison) '
CONDA_PYTHON_EXE=/Users/abhichaturvedi/miniconda3/bin/python
CONDA_SHLVL=2
DISPLAY=/private/tmp/com.apple.launchd.J6LOZdiYs6/org.xquartz:0
DYLD_LIBRARY_PATH=/opt/homebrew/opt/libomp/lib:
HOME=/Users/abhichaturvedi
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_REPOSITORY=/opt/homebrew
INFOPATH=/opt/homebrew/share/info:
ITERM_PROFILE=scalenow-AI
ITERM_SESSION_ID=w1t0p0:EFA7704E-B7BD-48F8-8FD3-BF36FE3BFF14
LANG=en_AU.UTF-8
LC_TERMINAL=iTerm2
LC_TERMINAL_VERSION=3.5.5
LESS=-R
LOGNAME=abhichaturvedi
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS='di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'
LaunchInstanceID=ED498D7A-30A8-4BAE-8F94-FE830EED1FCC
OLDPWD=/Users/abhichaturvedi/miniconda3
OPENAI_API_KEY="removed the key"
P9K_SSH=0
P9K_TTY=old
PAGER=less
PATH=/Users/abhichaturvedi/miniconda3/envs/praison/bin:/Users/abhichaturvedi/miniconda3/condabin:/opt/homebrew/bin:/Users/abhichaturvedi/Library/pnpm:/opt/homebrew/bin:/opt/homebrew/bin:/usr/local/bin:/Users/abhichaturvedi/.rbenv/shims:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Users/abhichaturvedi/appflowy/development/flutter/bin:/Users/abhichaturvedi/.cargo/bin:/Users/abhichaturvedi/Applications/iTerm.app/Contents/Resources/utilities:/Users/abhichaturvedi/.cache/lm-studio/bin:/Users/abhichaturvedi/.pub-cache/bin:/Users/abhichaturvedi/.cache/lm-studio/bin
PNPM_HOME=/Users/abhichaturvedi/Library/pnpm
PWD=/Users/abhichaturvedi/miniconda3/envs
RBENV_SHELL=zsh
SECURITYSESSIONID=186b1
SHELL=/bin/zsh
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.1mfjiZv201/Listeners
TERM=xterm-256color
TERMINFO_DIRS=/Users/abhichaturvedi/Applications/iTerm.app/Contents/Resources/terminfo:/usr/share/terminfo
TERM_FEATURES=T3CwLrMSc7UUw9Ts3BFGsSyHNoSxF
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.5.5
TERM_SESSION_ID=w1t0p0:EFA7704E-B7BD-48F8-8FD3-BF36FE3BFF14
TMPDIR=/var/folders/6v/7wvmt1m979gg4nl1kn6qr6rh0000gn/T/
USER=abhichaturvedi
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
ZSH=/Users/abhichaturvedi/.oh-my-zsh
_CE_CONDA=''
_CE_M=''
_P9K_SSH_TTY=/dev/ttys001
_P9K_TTY=/dev/ttys001
__CFBundleIdentifier=com.googlecode.iterm2
__CF_USER_TEXT_ENCODING=0x0:0:15

python -m praisonai ui

2024-12-07 13:36:30,038 - 8303441984 - __init__.py-__init__:1231 - WARNING: SDK is disabled.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/lib/python3.11/site-packages/praisonai/__main__.py", line 10, in <module>
    main()
  File "/opt/homebrew/lib/python3.11/site-packages/praisonai/__main__.py", line 7, in main
    praison_ai.main()
  File "/opt/homebrew/lib/python3.11/site-packages/praisonai/cli.py", line 122, in main
    args = self.parse_args()
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/praisonai/cli.py", line 372, in parse_args
    self.create_chainlit_interface()
  File "/opt/homebrew/lib/python3.11/site-packages/praisonai/cli.py", line 476, in create_chainlit_interface
    chainlit_run([chainlit_ui_path])
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 201, in chainlit_run
    run_chainlit(target)
  File "/opt/homebrew/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 68, in run_chainlit
    ensure_jwt_secret()
  File "/opt/homebrew/lib/python3.11/site-packages/chainlit/auth.py", line 22, in ensure_jwt_secret
    raise ValueError(
ValueError: You must provide a JWT secret in the environment to use authentication. Run `chainlit create-secret` to generate one.

**Comment by scalenow** [comment]
Problem Solved

**Comment by scalenow** [comment]
Problem Solved
