### ISSUE TITLE
praisonai --init "create a movie script about dog in moon" throws error

### ISSUE THREAD

**Issue by starascendin** [MervinPraison/PraisonAI#203]
praisonai --init "create a movie script about dog in moon"
/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py:777: UserWarning: Mixing V1 models and V2 models (or constructs, like `TypeAdapter`) is not supported. Please upgrade `CrewAgentExecutor` to V2.
  warn(
Traceback (most recent call last):
  File "/Users/bryanliu/.pyenv/versions/3.11.5/bin/praisonai", line 5, in <module>
    from praisonai.__main__ import main
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/praisonai/__init__.py", line 5, in <module>
    from .cli import PraisonAI
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/praisonai/cli.py", line 39, in <module>
    from chainlit.cli import chainlit_run
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/chainlit/__init__.py", line 18, in <module>
    from chainlit.action import Action
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/chainlit/action.py", line 5, in <module>
    from chainlit.telemetry import trace_event
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/chainlit/telemetry.py", line 12, in <module>
    from chainlit.config import config
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/chainlit/config.py", line 523, in <module>
    config = load_config()
             ^^^^^^^^^^^^^
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/chainlit/config.py", line 492, in load_config
    settings = load_settings()
               ^^^^^^^^^^^^^^^
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/chainlit/config.py", line 464, in load_settings
    code_settings = CodeSettings(action_callbacks={})
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py", line 121, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryanliu/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pydantic/_internal/_mock_val_ser.py", line 100, in __getattr__
    raise PydanticUserError(self._error_message, code=self._code)
pydantic.errors.PydanticUserError: `CodeSettings` is not fully defined; you should define `Action`, then call `pydantic.dataclasses.rebuild_dataclass(CodeSettings)`.

For further information visit https://errors.pydantic.dev/2.10/u/class-not-fully-defined

**Comment by starascendin** [comment]
ran into this issue no matter how many times i tried w/ different venv and conda env

**Comment by starascendin** [comment]
i ran it on my other mac and it worked... might be my own local dev env issue
