### ISSUE TITLE
ImportError: cannot import name 'BaseStorageClient' from 'chainlit.data.base' 

### ISSUE THREAD

**Issue by atxcowboy** [MervinPraison/PraisonAI#221]
I am getting the following error on `praisonai realtime`

```
[19:48:50] INFO     [19:48:50] cli.py:504 INFO Public folder already exists.                                                                                                                           cli.py:504
           WARNING  [19:48:50] __init__.py:1231 WARNING SDK is disabled.                                                                                                                         __init__.py:1231
Traceback (most recent call last):
  File "/home/karateka/miniconda3/envs/praisonai/bin/praisonai", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/praisonai/__main__.py", line 7, in main
    praison_ai.main()
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/praisonai/cli.py", line 136, in main
    args = self.parse_args()
           ^^^^^^^^^^^^^^^^^
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/praisonai/cli.py", line 373, in parse_args
    self.create_realtime_interface()
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/praisonai/cli.py", line 506, in create_realtime_interface
    chainlit_run([realtime_ui_path])
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 214, in chainlit_run
    run_chainlit(target)
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/chainlit/cli/__init__.py", line 78, in run_chainlit
    load_module(config.run.module_name)
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/chainlit/config.py", line 453, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/praisonai/ui/realtime.py", line 14, in <module>
    from sql_alchemy import SQLAlchemyDataLayer
  File "/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/praisonai/ui/sql_alchemy.py", line 12, in <module>
    from chainlit.data.base import BaseDataLayer, BaseStorageClient
ImportError: cannot import name 'BaseStorageClient' from 'chainlit.data.base' (/home/karateka/miniconda3/envs/praisonai/lib/python3.11/site-packages/chainlit/data/base.py)

```

**Comment by SaisaranF22** [comment]
same happened to me, try uninstall then reinstall chainlit. it works

**Comment by atxcowboy** [comment]
Unfortunately this did not work. I get the same error on a fresh installation on another machine. It looks like the latest versions of Praisonai, Chainlit, Pydantic and Instructor are not aligned?

**Comment by jasonkneen** [comment]
Same problem, round and around in circles

**Comment by structops** [comment]
Facing this too.  Hope it can be resolved quickly.

**Comment by MervinPraison** [comment]
@atxcowboy @jasonkneen @structops Please upgrade the package and it should work. 

Please reopen this if you continue to experience issues.
