### ISSUE TITLE
PraisonAI is not running with ollama model mistral or llama3 on windows 11

### ISSUE THREAD

**Issue by ziayounasch** [MervinPraison/PraisonAI#38]
when I run the praisonai --init command I get the following error even I have set the environment variables:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ziach\anaconda3\envs\praisonaiagents\Scripts\praisonai.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ziach\anaconda3\envs\praisonaiagents\Lib\site-packages\praisonai\__main__.py", line 7, in main
    praison_ai.main()
  File "C:\Users\Ziach\anaconda3\envs\praisonaiagents\Lib\site-packages\praisonai\cli.py", line 68, in main
    generator = AutoGenerator(topic=self.topic , framework=self.framework, agent_file=self.agent_file)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ziach\anaconda3\envs\praisonaiagents\Lib\site-packages\praisonai\auto.py", line 37, in __init__
    OpenAI(
  File "C:\Users\Ziach\anaconda3\envs\praisonaiagents\Lib\site-packages\openai\_client.py", line 104, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable`

**Comment by HyperUpscale** [comment]
You dont seem to have provided OPEN API key... 
The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable.
follow this video - it explains all the steps:
https://www.youtube.com/watch?v=wJzeg6IUzJY&t=360s&ab_channel=FahdMirza

**Comment by MervinPraison** [comment]
Thanks for all your contributions. This issue was fixed earlier. @ziayounasch @HyperUpscale
