### ISSUE TITLE
Problem running 'praisonai --init create a movie script about dog in moon  '

### ISSUE THREAD

**Issue by joliva** [MervinPraison/praisonAI#4]
pip install praisonai

Environment:
MacOS Sonoma
Python 3.11
Ollama server running
OPENAI_API_KEY=fake
OPENAI_API_BASE=http://localhost:11434/api/generate
OPENAI_MODEL_NAME=mistral

Run Output:

Traceback (most recent call last):
  File "/Users/joliva/.pyenv/versions/3.11.6/bin/praisonai", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/praisonai/__main__.py", line 7, in main
    praison_ai.main()
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/praisonai/cli.py", line 154, in main
    self.agent_file = generator.generate()
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/praisonai/auto.py", line 44, in generate
    response = self.client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/instructor/patch.py", line 570, in new_create_sync
    response = retry_sync(
               ^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/instructor/patch.py", line 387, in retry_sync
    for attempt in max_retries:
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/instructor/patch.py", line 390, in retry_sync
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/openai/_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/openai/_base_client.py", line 897, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/openai/_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: 404 page not found

**Comment by franciscoabenza** [comment]
what version of openai are you using? `openai -V`

**Comment by jyonny-byte** [comment]
You need to use OPENAI_BASE_URL=http://localhost:11434/v1 

Not /api/generate when making openai structure calls

**Comment by joliva** [comment]
> OPENAI_API_BASE=http://localhost:11434/v1

That was the ticket - thank!

**Comment by unijoy** [comment]
this lie "
File "/Users/joliva/.pyenv/versions/3.11.6/lib/python3.11/site-packages/praisonai/auto.py", line 44, in generate
response = self.client.chat.completions.create(
"

seems you need to check your "http://localhost:11434/v1" server , using curl if it is ok
