### ISSUE TITLE
Bug: TypeError: str expected, not NoneType

### ISSUE THREAD

**Issue by MervinPraison** [MervinPraison/PraisonAI#54]
RuntimeError: StaticFiles directory 'public' does not exist.
2024-06-19 22:43:33,142 - 8622177088 - utils.py-utils:50 - ERROR: str expected, not NoneType
Traceback (most recent call last):
  File "/Users/praison/.pyenv/versions/3.11.0/lib/python3.11/site-packages/chainlit/utils.py", line 44, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/praison/.pyenv/versions/3.11.0/lib/python3.11/site-packages/praisonai/chainlit_ui.py", line 143, in start_chat
    await on_settings_update(settings)
  File "/Users/praison/.pyenv/versions/3.11.0/lib/python3.11/site-packages/praisonai/chainlit_ui.py", line 152, in on_settings_update
    os.environ["OPENAI_API_KEY"] = config_list[0]['api_key']
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 683, in __setitem__
  File "<frozen os>", line 757, in encode
TypeError: str expected, not NoneType

**Comment by MervinPraison** [comment]
Fixed this issue in this release https://github.com/MervinPraison/PraisonAI/releases/tag/v0.0.33
