### ISSUE TITLE
There's a problem with the implementation of the litellm library for Gemini for this project 

### ISSUE THREAD

**Issue by RFARREY** [MervinPraison/PraisonAI#98]
├── utils.h
        ├── win32_window.cpp
        └── win32_window.h
2024-07-17 17:21:21,675 - 9536 - utils.py-utils:50 - ERROR: litellm.BadRequestError: GetLLMProvider Exception - list index out of range

original model: gemini
Traceback (most recent call last):
  File "D:\MY FLUTTER DEV PROJECTS\shopping_list_app\HERB_APP\HERB_GROWING_COMMUNITY_SHARING\herb_community_sharing_scheme\budgrowX\Lib\site-packages\litellm\utils.py", line 4353, in get_llm_provider
    model = model.split("/", 1)[1]
            ~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MY FLUTTER DEV PROJECTS\shopping_list_app\HERB_APP\HERB_GROWING_COMMUNITY_SHARING\herb_community_sharing_scheme\budgrowX\Lib\site-packages\chainlit\utils.py", line 44, in wrapper 
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MY FLUTTER DEV PROJECTS\shopping_list_app\HERB_APP\HERB_GROWING_COMMUNITY_SHARING\herb_community_sharing_scheme\budgrowX\Lib\site-packages\praisonai\ui\code.py", line 245, in main
    response = await acompletion(
               ^^^^^^^^^^^^^^^^^^
  File "D:\MY FLUTTER DEV PROJECTS\shopping_list_app\HERB_APP\HERB_GROWING_COMMUNITY_SHARING\herb_community_sharing_scheme\budgrowX\Lib\site-packages\litellm\utils.py", line 1505, in wrapper_async
    raise e
  File "D:\MY FLUTTER DEV PROJECTS\shopping_list_app\HERB_APP\HERB_GROWING_COMMUNITY_SHARING\herb_community_sharing_scheme\budgrowX\Lib\site-packages\litellm\utils.py", line 1317, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MY FLUTTER DEV PROJECTS\shopping_list_app\HERB_APP\HERB_GROWING_COMMUNITY_SHARING\herb_community_sharing_scheme\budgrowX\Lib\site-packages\litellm\main.py", line 338, in acompletion
    _, custom_llm_provider, _, _ = get_llm_provider(
                                   ^^^^^^^^^^^^^^^^^
  File "D:\MY FLUTTER DEV PROJECTS\shopping_list_app\HERB_APP\HERB_GROWING_COMMUNITY_SHARING\herb_community_sharing_scheme\budgrowX\Lib\site-packages\litellm\utils.py", line 4531, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: GetLLMProvider Exception - list index out of range

original model: gemini

**Comment by MervinPraison** [comment]
@RFARREY Can you please try running this is WSL inside windows?
